name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.KEY }}
  PASSPHRASE: ${{ secrets.PASSPHRASE }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
        passphrase: ${{ env.PASSPHRASE }}

    - name: Run script on remote server
      uses: webfactory/ssh-actions@v0.4.0
      with:
        ssh-user: ${{ secrets.USERNAME }}
        ssh-host: ${{ secrets.HOST }}
        ssh-key: ${{ env.SSH_PRIVATE_KEY }}
        script: |
          pwd
          whoami
          echo "Running script on remote server"
