name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Deploy-Script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: executing script
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              whoami
              pwd
