name: CD

on:
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  Deploy-Script:
    runs-on: ubuntu-latest

    steps:
      - name: executing script
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            passphrase: ${{ secrets.PASSPHRASE }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              cd /home/afifosh/public_html/pms.afifosh.com
              git checkout staging
              git reset --hard origin/staging
              git pull origin staging
              rm .env -f
              cp .env.server .env
              composer install --no-ansi --no-interaction --no-plugins --no-progress --no-scripts --optimize-autoloader
              php -d  memory_limit=128M artisan storage:link --force
              php -d  memory_limit=128M artisan migrate:fresh --force
              php -d  memory_limit=512M artisan db:seed --force
              nvm use 16 && yarn
              yarn prod
